import { test, expect } from '@playwright/test';

test('Home', async ({ page }) => {
  await page.goto('https://dokan-testing.netlify.app/auth');
  await page.getByPlaceholder('XXXXXXXXXX').click();
  await page.getByPlaceholder('XXXXXXXXXX').fill('01966866176');
  await page.getByRole('button', { name: 'এগিয়ে যান' }).click();
  await page.locator('#current_password').fill('12345');
  await page.getByRole('button', { name: 'লগইন করুন' }).click();
  await page.getByRole('button', { name: 'সিলেক্ট করুন' }).first().click();
  await page.getByRole('link', { name: 'হোম' }).click();
  await page.getByRole('link', { name: 'কেনা', exact: true }).click();
  await page.getByRole('link', { name: 'বেচা', exact: true }).click();
  await page.getByRole('link', { name: 'ক্যাশবক্স' }).click();
  await page.getByRole('button', { name: 'দ্রুত বেচা' }).click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByRole('link', { name: 'কেনার খাতা' }).click();
  await page.getByRole('link', { name: 'বেচার খাতা' }).click();
  await page.getByRole('link', { name: 'বাকির খাতা' }).click();
  await page.getByRole('link', { name: 'খরচের খাতা' }).click();
  await page.getByRole('link', { name: 'যোগাযোগ' }).click();
  await page.getByRole('link', { name: 'অ্যাপ ট্রেনিং' }).click();
  await page.getByRole('link', { name: 'প্রোডাক্ট লিস্ট' }).click();
  await page.getByRole('link', { name: 'স্টকের হিসাব' }).click();
  await page.getByRole('link', { name: 'অ্যাপ অ্যাক্সেস' }).click();
  await page.getByRole('link', { name: 'প্রিন্টার' }).click();
  await page.getByRole('link', { name: 'ব্যবসার রিপোর্ট' }).click();
  await page.getByRole('link', { name: 'মার্কেটিং' }).click();
  await page.getByRole('link', { name: 'অনলাইন শপ' }).click();
  await page.getByRole('link', { name: 'মেয়াদোত্তীর্ণ পণ্য' }).click();
  await page.getByRole('link', { name: 'ওয়ারেন্টি পণ্য' }).click();
  await page.getByRole('link', { name: 'রিসাইকেল বিন' }).click();
  await page.getByRole('button').nth(2).click();
  await page.getByRole('button').nth(3).click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByRole('button', { name: 'সেটিংস' }).click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByText('test', { exact: true }).click();
  await page.locator('#root').getByText('test', { exact: true }).click();
  await page.locator('svg').nth(5).click();
  await page.locator('svg').nth(5).click();
});
